language: python
python:
- '3.6'
sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
before_install:
- docker version
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i "s/appdev./ci./" test_local/test.cfg
script:
- kb-sdk test
after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/handle_service2 /kb/module/lib/
- coverage report -m
- coveralls
env:
  global:
  - secure: TZobEVrnFLW0ywekL5RkDq2sVOuKmVenabfksAsY4FXAgdft2foAeMTx2ncw5wSfDUfdeHe2TpYhaPyJnCfytNNt0X1TN/2BMLQcdnbs3Io+9jDz9etf0SLxQbypdsSt/J/6kb7vovH6chFzB5UPtT+u/cIkSDSwHUT0lUVVWP2/b/1Kc5AqYyBD1gLiAIkvNgXMqh+DE8qUsahjKs0gi2z+m7h2+cOoj4Yz0p275BWw2cUebS2XHUM40GtTZfj///zmgj5B4cnJKhacEs6+pVwszrMw7YKGby+TUmimTrOwR6BIbWe/Q2z32ArgOL3YuxPIt6+Lw75lY5oOub1uLlABkmMm5Xeg+izZ9/hhSD/nse5PUDvCXlKEkKbDhqtT+Vz4cipDY/I+R57mYy6MLtwfeieoyjxb32ixfSTQMvbQ+LJJVBUtgRkc/vcfQoBnk0383QjBw6Yc6LA9Hg5KU3bpnHIT1dYiI4kOzNhHzyBGRTCJE/w8vKs4uEusEfMEz3j7mieaWypxIgNh66vbSm2GMTsQ7YpsgNEt0CkykXNLwQW4uUV8Ga08pE5waasBwTPLjF6Rar0yinANbgpm5SZZCwe0G1dDpszQ0r67RVITsxDpfz8rhf22Z1JHNE8WclEXAUnwSmsWEFfA2XRk4VpS0cc/e5qqYcCeS3tzAcc=
